Repository DFE-Digital/school-account, pull requests merged in 2023-05, with the labels that each got.

#3 Initial commit of 'linked-templates' directory on behalf of Akash.
  DevOps/linked-templates/app-insights.json
  DevOps/linked-templates/app-service.json
Labels: enhancement

#4 Add main/parent template on behalf of Akash.
  DevOps/pipeline/azure-pipeline.yml
  DevOps/templates/maintemplate.json
Labels: enhancement

#5 environmentId default value set to d01
  DevOps/templates/maintemplate.json
Labels: enhancement

#6 Fix bug in app-servive linked template
  DevOps/linked-templates/app-service.json
Labels: bug

#7 Add GitHub workflow for automatically building and testing the .NET projects.
  .github/workflows/dotnet-tests.yml
Labels: enhancement

#8 create one template for all resource deployment
  .DS_Store
  DevOps/.DS_Store
  DevOps/linked-templates/app-insights.json
  DevOps/linked-templates/app-service.json
  DevOps/powershell/create-resource-group.ps1
  DevOps/powershell/deploy-template-locally.ps1
  DevOps/templates/SchoolAccountArm.json
  DevOps/templates/SchoolAccountArm.parameters.json
  DevOps/templates/maintemplate.json
Labels: enhancement

#12 Add "Run unit tests" section to the 'README.md' file.
  README.md
Labels: documentation

#13 Add feature to restrict access to school users
  Dfe.SchoolAccount.SignIn.Tests/Extensions/ClaimExtensionsTests.cs
  Dfe.SchoolAccount.SignIn/Extensions/ClaimExtensions.cs
  Dfe.SchoolAccount.Web.Tests/Authorization/RestrictToSchoolUsersAuthorizationHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Authorization/RestrictedAccessAuthorizationHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Controllers/AccountControllerTests.cs
  Dfe.SchoolAccount.Web.Tests/Controllers/HomeControllerTests.cs
  Dfe.SchoolAccount.Web.Tests/Fakes/FakePersonaResolver.cs
  Dfe.SchoolAccount.Web.Tests/Fakes/UserFakesHelper.cs
  Dfe.SchoolAccount.Web.Tests/Services/OrganisationPersonaResolverTests.cs
  Dfe.SchoolAccount.Web/Authorization/RestrictToSchoolUsersAuthorizationHandler.cs
  Dfe.SchoolAccount.Web/Authorization/RestrictedAccessAuthorizationHandler.cs
  Dfe.SchoolAccount.Web/Controllers/HomeController.cs
  Dfe.SchoolAccount.Web/Program.cs
  Dfe.SchoolAccount.Web/Services/Personas/IPersonaResolver.cs
  Dfe.SchoolAccount.Web/Services/Personas/OrganisationPersonaResolver.cs
Labels: enhancement

#14 Use `AddAzureKeyVault` to access configuration from a configured Azure Key Vault
  Dfe.SchoolAccount.Web/Dfe.SchoolAccount.Web.csproj
  Dfe.SchoolAccount.Web/Program.cs
  Dfe.SchoolAccount.Web/appsettings.json
Labels: enhancement

#15 Backup azure-devops pipelines
  DevOps/pipeline/S191-DfESchoolAccount-ARM-CI.yml
  DevOps/pipeline/S191-DfESchoolAccount-ASP.NETCore-DEV-CI.yml
  DevOps/pipeline/azure-pipeline.yml
Labels: enhancement

#17 Report code coverage with SonarCloud Scanner
  .github/workflows/dotnet-tests.yml
Labels: enhancement

#19 Replace coverlet coverage testing with dotnet-coverage
  .github/workflows/dotnet-tests.yml
  .gitignore
  coverage.settings.xml
  coverlet.runsettings.xml
Labels: enhancement

#16 Add "Get school business information" and "Useful services and guidance" cards to the home page
  Dfe.SchoolAccount.Web.Tests/Controllers/HomeControllerTests.cs
  Dfe.SchoolAccount.Web.Tests/Dfe.SchoolAccount.Web.Tests.csproj
  Dfe.SchoolAccount.Web.Tests/Helpers/ViewHelpersTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Content/ContentfulHubContentFetcherTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Personas/OrganisationPersonaResolverTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Personas/UnknownPersonaExceptionTests.cs
  Dfe.SchoolAccount.Web.Tests/TestHelpers/TypeAssert.cs
  Dfe.SchoolAccount.Web.Tests/TestHelpers/UserFakesHelper.cs
  Dfe.SchoolAccount.Web/Constants/HubConstants.cs
  Dfe.SchoolAccount.Web/Controllers/HomeController.cs
  Dfe.SchoolAccount.Web/Dfe.SchoolAccount.Web.csproj
  Dfe.SchoolAccount.Web/Frontend/scss/components/card.scss
  Dfe.SchoolAccount.Web/Frontend/scss/main.scss
  Dfe.SchoolAccount.Web/Helpers/ViewHelpers.cs
  Dfe.SchoolAccount.Web/Models/Content/CardContent.cs
  Dfe.SchoolAccount.Web/Models/Content/HubContent.cs
  Dfe.SchoolAccount.Web/Models/HomeViewModel.cs
  Dfe.SchoolAccount.Web/Models/Partials/CardsPartialViewModel.cs
  Dfe.SchoolAccount.Web/Program.cs
  Dfe.SchoolAccount.Web/Resources/Views/Home/Index.cy.resx
  Dfe.SchoolAccount.Web/Resources/Views/Home/Index.en.resx
  Dfe.SchoolAccount.Web/Services/Content/ContentfulHubContentFetcher.cs
  Dfe.SchoolAccount.Web/Services/Content/IHubContentFetcher.cs
  Dfe.SchoolAccount.Web/Services/Personas/UnknownPersonaException.cs
  Dfe.SchoolAccount.Web/Views/Home/Index.cshtml
  Dfe.SchoolAccount.Web/Views/Shared/Partials/_Cards.cshtml
  Dfe.SchoolAccount.Web/Views/Shared/_Layout.cshtml
  Dfe.SchoolAccount.Web/Views/_ViewImports.cshtml
  Dfe.SchoolAccount.Web/appsettings.json
Labels: enhancement

#20 Implement signposting pages
  Dfe.SchoolAccount.Web.Tests/Controllers/HomeControllerTests.cs
  Dfe.SchoolAccount.Web.Tests/Controllers/SignpostingPageControllerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Content/ContentfulHubContentFetcherTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Content/ContentfulSignpostingPageContentFetcherTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Content/CustomContentTypeResolverTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentTransformers/Cards/ExternalResourceContentToCardTransformHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentTransformers/Cards/SignpostingPageContentToCardTransformHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentTransformers/ContentModelTransformerExtensionsTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentTransformers/RegisteredServicesContentModelTransformerTests.cs
  Dfe.SchoolAccount.Web/Constants/ContentTypeConstants.cs
  Dfe.SchoolAccount.Web/Controllers/HomeController.cs
  Dfe.SchoolAccount.Web/Controllers/SignpostingController.cs
  Dfe.SchoolAccount.Web/Models/Content/CardGroupModel.cs
  Dfe.SchoolAccount.Web/Models/Content/CardModel.cs
  Dfe.SchoolAccount.Web/Models/Content/ExternalResourceContent.cs
  Dfe.SchoolAccount.Web/Models/Content/HubContent.cs
  Dfe.SchoolAccount.Web/Models/Content/SignpostingPageContent.cs
  Dfe.SchoolAccount.Web/Models/HomeViewModel.cs
  Dfe.SchoolAccount.Web/Models/Partials/CardsPartialViewModel.cs
  Dfe.SchoolAccount.Web/Models/SignpostingPageViewModel.cs
  Dfe.SchoolAccount.Web/Program.cs
  Dfe.SchoolAccount.Web/Services/Content/ContentfulHubContentFetcher.cs
  Dfe.SchoolAccount.Web/Services/Content/ContentfulSignpostingPageContentFetcher.cs
  Dfe.SchoolAccount.Web/Services/Content/CustomContentTypeResolver.cs
  Dfe.SchoolAccount.Web/Services/Content/ISignpostingPageContentFetcher.cs
  Dfe.SchoolAccount.Web/Services/ContentTransformers/Cards/ExternalResourceContentToCardTransformHandler.cs
  Dfe.SchoolAccount.Web/Services/ContentTransformers/Cards/SignpostingPageContentToCardTransformHandler.cs
  Dfe.SchoolAccount.Web/Services/ContentTransformers/ContentModelTransformerExtensions.cs
  Dfe.SchoolAccount.Web/Services/ContentTransformers/IContentModelTransformHandler{TContent, TTargetModel}.cs
  Dfe.SchoolAccount.Web/Services/ContentTransformers/IContentModelTransformer.cs
  Dfe.SchoolAccount.Web/Services/ContentTransformers/RegisteredServicesContentModelTransformer.cs
  Dfe.SchoolAccount.Web/Services/Rendering/CardGroupModelRenderer.cs
  Dfe.SchoolAccount.Web/Services/Rendering/CustomHeadingRenderer.cs
  Dfe.SchoolAccount.Web/Views/Shared/Partials/_Cards.cshtml
  Dfe.SchoolAccount.Web/Views/Signposting/Index.cshtml
  Dfe.SchoolAccount.Web/Views/_ViewImports.cshtml
Labels: enhancement

#22 Add section on configuring Contentful space secrets
  README.md
Labels: documentation

#21 Adjust organisation category and establishment type mappings.
  Dfe.SchoolAccount.Web.Tests/Services/Personas/OrganisationPersonaResolverTests.cs
  Dfe.SchoolAccount.Web/Services/Personas/OrganisationPersonaResolver.cs
Labels: enhancement

#23 Add general error page content with a special case for "Your institution is not yet eligible for this service"
  Dfe.SchoolAccount.Web.Tests/Authorization/FailedAuthorizationMiddlewareResultHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Controllers/ErrorPageControllerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Content/ContentfulErrorPageContentFetcherTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Content/ContentfulHubContentFetcherTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/Content/ContentfulSignpostingPageContentFetcherTests.cs
  Dfe.SchoolAccount.Web/Authorization/FailedAuthorizationMiddlewareResultHandler.cs
  Dfe.SchoolAccount.Web/Authorization/RestrictToSchoolUsersAuthorizationHandler.cs
  Dfe.SchoolAccount.Web/Authorization/RestrictedAccessAuthorizationHandler.cs
  Dfe.SchoolAccount.Web/Constants/AuthorizationFailureConstants.cs
  Dfe.SchoolAccount.Web/Constants/ContentTypeConstants.cs
  Dfe.SchoolAccount.Web/Constants/ErrorPageConstants.cs
  Dfe.SchoolAccount.Web/Controllers/ErrorPageController.cs
  Dfe.SchoolAccount.Web/Models/Content/ErrorPageContent.cs
  Dfe.SchoolAccount.Web/Program.cs
  Dfe.SchoolAccount.Web/Services/Content/ContentfulErrorPageContentFetcher.cs
  Dfe.SchoolAccount.Web/Services/Content/IErrorPageContentFetcher.cs
  Dfe.SchoolAccount.Web/Services/Content/ISignpostingPageContentFetcher.cs
  Dfe.SchoolAccount.Web/Views/ErrorPage/Index.cshtml
Labels: enhancement

#27 Exclude '.DS_Store' files from the repository.
  .DS_Store
  .gitignore
  DevOps/.DS_Store
Labels: enhancement

#26 Add feature to resolve hyperlinks to content entries
  Dfe.SchoolAccount.Web.Tests/Services/Content/CustomContentTypeResolverTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentHyperlinks/Handlers/ExternalResourceContentHyperlinkResolutionHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentHyperlinks/Handlers/PageContentHyperlinkResolutionHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentHyperlinks/Handlers/SignpostingPageContentHyperlinkResolutionHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentHyperlinks/RegisteredServicesContentHyperlinkResolverTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentTransformers/Cards/SignpostingPageContentToCardTransformHandlerTests.cs
  Dfe.SchoolAccount.Web.Tests/Services/ContentTransformers/RegisteredServicesContentModelTransformerTests.cs
  Dfe.SchoolAccount.Web/Models/Content/CardModel.cs
  Dfe.SchoolAccount.Web/Program.cs
  Dfe.SchoolAccount.Web/Services/Content/CustomContentTypeResolver.cs
  Dfe.SchoolAccount.Web/Services/ContentHyperlinks/ContentHyperlink.cs
  Dfe.SchoolAccount.Web/Services/ContentHyperlinks/Handlers/ExternalResourceContentHyperlinkResolutionHandler.cs
  Dfe.SchoolAccount.Web/Services/ContentHyperlinks/Handlers/PageContentHyperlinkResolutionHandler.cs
  Dfe.SchoolAccount.Web/Services/ContentHyperlinks/Handlers/SignpostingPageContentHyperlinkResolutionHandler.cs
  Dfe.SchoolAccount.Web/Services/ContentHyperlinks/IContentHyperlinkResolutionHandler{TContent}.cs
  Dfe.SchoolAccount.Web/Services/ContentHyperlinks/IContentHyperlinkResolver.cs
  Dfe.SchoolAccount.Web/Services/ContentHyperlinks/RegisteredServicesContentHyperlinkResolver.cs
  Dfe.SchoolAccount.Web/Services/ContentTransformers/Cards/SignpostingPageContentToCardTransformHandler.cs
  Dfe.SchoolAccount.Web/Services/Rendering/ContentLinkRenderer.cs
  Dfe.SchoolAccount.Web/Views/Shared/Partials/_Cards.cshtml
Labels: enhancement
